language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: XJbfiFBWyuk3PxLFrTavUKePNJuXbmNG1cJZ3qWdkmInxqr81wxX0+DkV1W+jm7glZErah9uC35323Q0IzEui69YYWbGNL8RANqM7sXyBb/Lutu28gjy7Ls4AP1/fCXpE3Bb5ftgzMyoROzrMg/My/uQZ7IargiiHh0QCIP5Cqu4BeWlmn4IQUORIIT2ZHVb46icS752vCQ6KbQOqVZiOES8ulsLexrCc9t0kOpPT1ET+q7v60yxITig4w5D1+DwQOIk55+2pPCXUOGJFbIC26f0lNK3xcoKBWydFaUh0tQckzBT4oYi6RdtLmxxhMjW95RZ3YnlrcCdQrH5Hci67Yvzf0cSmEuymA5QjGwYrZJsncuc+flT8JNnU9tzN6pPB+whzrXKC1hTJztmKaPsC2zZRpMMxtFu8QhCgKe6/bTY4l1jQai5P4ML8Esib2v0S96LP58GWr6iT35YIqMkJjTgP2RlFbVRP/B+Js7FrpeSRX199QrKDTODy/3IlSmq68k3bheThBo/yUHp5DL6OyV6pv9j0XlGD3UT4FBWG8GvBBXyoU/48SbWwMCG+9nNvi529NDxb6l/WkTXdWYmjJlhLyrNtiU/PqwtIwvB1BNBhPkd0seDkInNMQY5+fnI4QKrrC3ptSnqVqtD5eLqNQSSwrLia6wTKH+E7N0vl/Y=
  app: serene-spire-84430
  on:
    repo: mkhoshnasib/fancy-react
