language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: Mb4dJWwAhr5Zv/HYO/i9miFndIMXx8eRZ7vzQWSeRqyw+OVkLJtV/coN+a4EYH2YxeoQCeNuvcz562ZcsWQ6utq4cSrgPBcH/Xrelykin9c3vLWdzcLO3di6r+cf+4eM3VDYQUP64epFZhOrv/uSMBXqvzPx+sxuL0yUbJuRq9SJRondcQhVFKT7rhWHsA9PqIPCQbF1pFRL9SdT2WR39F8IKkrv5pHGkbQXIiFxaqALBhCXXW0w1cbMXuucGAgehfiPqLkREmVRNySRxh62qNHIcS1WmERqfuxc4VxuAnk6uMfy39ql/6b8QJcC8SqmaD1OsE5dxS9BBO0yBRYq1OZX1QkatNpfm2p7a3GEuhdB3/364rLHoikSlpjIXLPBcHTaMGmBEBPWkbDFawALJm3lkROZ/mmdMUHr1hi2rsyBAlDgNrBNBdbf2r4t+o4Jpuh7wVzuDTa4YqKHvs4KuvIIypcZ4T/US0Tlv2Mj9L+/Jy+62K1OrWzNf/5Vs+pndMrkFAfvBrf42iK33dhQGJnLKi3+ewr9TEK+AEG943NI+sjLGmcINk4DkXG0k81b97dPssXHmnB+AoTDkxuSvWq7f0kzKGXBNioD2Nk7IzL502EgWSsfZvFi2tqg26YrRdWpXEU4SViU+t3UXa697X7opPwnH9X6LqywEuoIjuU=
  app:
    master: fancy-react

