language: node_js
node_js:
- '8'
deploy:
  provider: heroku
  api_key:
    secure: I92Od53kwhsVyE2TIK6hJoWhJ6sq5VU8DHFEuKbByJZCGWRzPHsLiHlAItGOTK6VMmbEiJwZfyoRbF+XFeT1leafi/ngdbodi4h5ZzSpazkmA5kR6ARP5nOw51Ns2C/8mDhafbB4FirHiK6hpQrJQP4BbS94Zgfvd8DWgGV/mer8XYrJCVqps+Qbg+yge66udkrne+BpZaMvzhA0QG5eOKNY6/LlJwy0HaRj/T77/28ZKjw57J0JDKgEmqTlD2/uIllkUXwYkNP6mF62gQNhCYPwgrYMF91vhmzBuVO0+I19Oebfk6FxOUSQsulgVDWKfsQM/nP7QBHagcglof6Pn6qJAXyu4cFRybPn0hEoUHE30+3KeQRK3KUtB1N9VPTF7+n9WU5gm3KT7jCFA9tV3FC2vXsstqTasbTwV7Biip3jf/a3VdqA80YbHzETxaWQe4MTbrgaCTly6P+dUONbjo4q5eoBcJ5AUoTqZezYaRl1Y/2qZF6RGJAOrooh2j/33GIjZUIabyNbjszy6GJTPjBnIsVeRwMXe1Bl8QTkb3TNjOYqzkhlWonmljIdpHgfCxFQD70OiUuLiYE+7sxZarUL4uiGxmC6WjAm9kTFjmJzvFq8JBoJPQw2Kk9jccKhC/oYov+cJrAfOG+ZwmbirGMX9UrIExPpYfgcC9gcalE=
  app: fancy-react
  on:
    repo: mkhoshnasib/fancy-react
